export const ADD_TO_CART_WISHLIST = 'ADD_TO_CART_WISHLIST';
export const REMOVE_FROM_CART_WISHLIST = 'REMOVE_FROM_CART_WISHLIST';
export const CHANGE_QTY_WISHLIST = 'CHANGE_QTY_WISHLIST';
export const HYDRATE_CART_WISHLIST = 'HYDRATE_CART_WISHLIST';
export const RESET_CART_WISHLIST = 'RESET_CART_WISHLIST';